Allow the user to disable print statements
el-dee/panda3d-openvr pull request #6
Opened 2020-09-11 19:02 UTC by zurgeg

This one is self-explanatory :)

2020-09-12 20:27 UTC, el-dee requested changes
Thanks for this, just one small remark to fix and I'll merge it.

2020-09-12 20:27 UTC, el-dee commented on p3dopenvr/p3dopenvr.py
> +    def __init__(self,verbose):
Could you add a space after the comma and set the default value for verbose to True

2020-09-12 23:38 UTC, zurgeg commented
Yep!

On Sat, Sep 12, 2020 at 4:27 PM LD <notifications@github.com> wrote:

> *@el-dee* requested changes on this pull request.
>
> Thanks for this, just one small remark to fix and I'll merge it.
> ------------------------------
>
> In p3dopenvr/p3dopenvr.py
> <https://github.com/el-dee/panda3d-openvr/pull/6#discussion_r487445464>:
>
> > @@ -22,8 +22,9 @@ def exitfunc():
>      openvr.shutdown()
>
>  class P3DOpenVR():
> -    def __init__(self):
> +    def __init__(self,verbose):
>
> Could you add a space after the comma and set the default value for
> verbose to True
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/el-dee/panda3d-openvr/pull/6#pullrequestreview-487254469>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ALDEQMWEMXDZVUXRZ7HUEILSFPKU3ANCNFSM4RID2Q7A>
> .
>

2020-09-13 21:01 UTC, el-dee approved these changes

2020-09-13 21:02 UTC, el-dee commented
Thanks, merged in https://github.com/el-dee/panda3d-openvr/commit/7957473da6efcc8a96760555691ba89e9186654d

2020-09-13 21:02 UTC, closed without merging